---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 16Gi
